#!/bin/bash
# deploy_all.sh — Deploy the three HTTPS servers and maze client
# for Team4 Maze App architecture
#
# Usage: bash deployment/deploy_all.sh
#
# Architecture:
#   Maze App (GameHat 10.170.8.189)
#       ├── HTTPS POST /telemetry → Logging Server  (10.170.8.101) [MongoDB]
#       ├── HTTPS POST /telemetry → Mini Pupper     (10.170.8.105) [ROS2]
#       └── HTTPS POST /mission   → AI Server       (10.170.8.109) [Redis]

set -e

echo "============================================"
echo "  Team4 Maze App — Full Deployment Script"
echo "============================================"
echo ""

# ──────────────────────────────────────
# Server credentials
# ──────────────────────────────────────
LOGGING_HOST="10.170.8.101"
LOGGING_USER="team4tt"

PUPPER_HOST="10.170.8.105"
PUPPER_USER="ubuntu"

AI_HOST="10.170.8.109"
AI_USER="team4tt"

GAMEHAT_HOST="10.170.8.189"
GAMEHAT_USER="pi"

DEPLOY_DIR="/tmp/maze_deploy"

# ──────────────────────────────────────
# 1. LOGGING SERVER (MongoDB)
# ──────────────────────────────────────
echo "═══════════════════════════════════════════"
echo " [1/4] Deploying LOGGING SERVER (${LOGGING_HOST})"
echo "       MongoDB + HTTPS on port 8446"
echo "═══════════════════════════════════════════"
echo "Run these commands on the Logging Server:"
echo ""
echo "  ssh ${LOGGING_USER}@${LOGGING_HOST}"
echo "  # password: pennstate4"
echo ""
echo "  # Install dependencies"
echo "  sudo apt update"
echo "  sudo apt install -y build-essential pkg-config libmicrohttpd-dev \\"
echo "       libgnutls28-dev libmongoc-dev libbson-dev"
echo ""
echo "  # Install and start MongoDB"
echo "  sudo apt install -y mongodb-org || sudo apt install -y mongodb"
echo "  sudo systemctl start mongod || sudo service mongodb start"
echo ""
echo "  # Create deploy directory"
echo "  mkdir -p ~/maze_server/certs"
echo ""
echo "  # Generate TLS certificates"
echo "  cd ~/maze_server/certs"
echo "  openssl req -x509 -newkey rsa:2048 -keyout server.key -out server.crt \\"
echo "      -days 365 -nodes -subj '/CN=${LOGGING_HOST}'"
echo ""
echo "  # Copy maze_https_mongo.c to ~/maze_server/"
echo "  # (use scp from your dev machine — see below)"
echo ""
echo "  # Build"
echo "  cd ~/maze_server"
echo "  gcc -O2 -Wall -Wextra -std=c11 maze_https_mongo.c -o maze_https_mongo \\"
echo "      \$(pkg-config --cflags --libs libmicrohttpd libmongoc-1.0)"
echo ""
echo "  # Run"
echo "  ./maze_https_mongo"
echo ""
echo "  # SCP command (run from your dev machine):"
echo "  scp https/maze_https_mongo.c ${LOGGING_USER}@${LOGGING_HOST}:~/maze_server/"
echo ""
echo ""

# ──────────────────────────────────────
# 2. MINI PUPPER (ROS2 Bridge)
# ──────────────────────────────────────
echo "═══════════════════════════════════════════"
echo " [2/4] Deploying MINI PUPPER (${PUPPER_HOST})"
echo "       ROS2 Bridge + HTTPS on port 8446"
echo "═══════════════════════════════════════════"
echo "Run these commands on the Mini Pupper:"
echo ""
echo "  ssh ${PUPPER_USER}@${PUPPER_HOST}"
echo "  # password: mangdang"
echo ""
echo "  # Install dependencies"
echo "  sudo apt update"
echo "  sudo apt install -y build-essential pkg-config libmicrohttpd-dev \\"
echo "       libgnutls28-dev"
echo ""
echo "  # Create deploy directory"
echo "  mkdir -p ~/maze_server/certs"
echo ""
echo "  # Generate TLS certificates"
echo "  cd ~/maze_server/certs"
echo "  openssl req -x509 -newkey rsa:2048 -keyout server.key -out server.crt \\"
echo "      -days 365 -nodes -subj '/CN=${PUPPER_HOST}'"
echo ""
echo "  # Copy maze_https_ros2_bridge.c to ~/maze_server/"
echo "  # (use scp from your dev machine — see below)"
echo ""
echo "  # Build"
echo "  cd ~/maze_server"
echo "  gcc -O2 -Wall -Wextra -std=c11 maze_https_ros2_bridge.c -o maze_https_ros2_bridge \\"
echo "      \$(pkg-config --cflags --libs libmicrohttpd)"
echo ""
echo "  # Run"
echo "  ./maze_https_ros2_bridge"
echo ""
echo "  # SCP command (run from your dev machine):"
echo "  scp https/maze_https_ros2_bridge.c ${PUPPER_USER}@${PUPPER_HOST}:~/maze_server/"
echo ""
echo ""

# ──────────────────────────────────────
# 3. AI SERVER (Redis)
# ──────────────────────────────────────
echo "═══════════════════════════════════════════"
echo " [3/4] Deploying AI SERVER (${AI_HOST})"
echo "       Redis + HTTPS on port 8446"
echo "═══════════════════════════════════════════"
echo "Run these commands on the AI Server:"
echo ""
echo "  ssh ${AI_USER}@${AI_HOST}"
echo "  # password: pennstate4"
echo ""
echo "  # Install dependencies"
echo "  sudo apt update"
echo "  sudo apt install -y build-essential pkg-config libmicrohttpd-dev \\"
echo "       libgnutls28-dev libhiredis-dev redis-server"
echo ""
echo "  # Start Redis"
echo "  sudo systemctl start redis-server || sudo service redis-server start"
echo "  redis-cli ping   # should return PONG"
echo ""
echo "  # Create deploy directory"
echo "  mkdir -p ~/maze_server/certs"
echo ""
echo "  # Generate TLS certificates"
echo "  cd ~/maze_server/certs"
echo "  openssl req -x509 -newkey rsa:2048 -keyout server.key -out server.crt \\"
echo "      -days 365 -nodes -subj '/CN=${AI_HOST}'"
echo ""
echo "  # Copy maze_https_redis.c to ~/maze_server/"
echo "  # (use scp from your dev machine — see below)"
echo ""
echo "  # Build"
echo "  cd ~/maze_server"
echo "  gcc -O2 -Wall -Wextra -std=c11 maze_https_redis.c -o maze_https_redis \\"
echo "      \$(pkg-config --cflags --libs libmicrohttpd hiredis)"
echo ""
echo "  # Run"
echo "  ./maze_https_redis"
echo ""
echo "  # SCP command (run from your dev machine):"
echo "  scp https/maze_https_redis.c ${AI_USER}@${AI_HOST}:~/maze_server/"
echo ""
echo ""

# ──────────────────────────────────────
# 4. GAMEHAT CONTROLLER (Maze Client)
# ──────────────────────────────────────
echo "═══════════════════════════════════════════"
echo " [4/4] Deploying MAZE CLIENT (${GAMEHAT_HOST})"
echo "       GameHat Controller"
echo "═══════════════════════════════════════════"
echo "Run these commands on the GameHat Controller:"
echo ""
echo "  ssh ${GAMEHAT_USER}@${GAMEHAT_HOST}"
echo "  # password: raspberry"
echo ""
echo "  # Install dependencies"
echo "  sudo apt update"
echo "  sudo apt install -y build-essential pkg-config libsdl2-dev \\"
echo "       libcurl4-openssl-dev libcjson-dev libhiredis-dev redis-server"
echo ""
echo "  # Start Redis (for local mission tracking)"
echo "  sudo systemctl start redis-server || sudo service redis-server start"
echo ""
echo "  # Create deploy directory"
echo "  mkdir -p ~/maze_app"
echo ""
echo "  # Copy maze_sdl2_final_send.c to ~/maze_app/"
echo "  # (use scp from your dev machine — see below)"
echo ""
echo "  # Build"
echo "  cd ~/maze_app"
echo "  gcc -O2 -Wall -std=c11 maze_sdl2_final_send.c -o maze_game \\"
echo "      \$(pkg-config --cflags --libs sdl2) -lcurl -lcjson -lhiredis"
echo ""
echo "  # Run"
echo "  ./maze_game"
echo ""
echo "  # SCP command (run from your dev machine):"
echo "  scp maze/maze_sdl2_final_send.c ${GAMEHAT_USER}@${GAMEHAT_HOST}:~/maze_app/"
echo ""
echo ""

# ──────────────────────────────────────
# Quick SCP all files
# ──────────────────────────────────────
echo "═══════════════════════════════════════════"
echo " QUICK SCP COMMANDS (run from dev machine)"
echo "═══════════════════════════════════════════"
echo ""
echo "# Logging Server:"
echo "scp https/maze_https_mongo.c ${LOGGING_USER}@${LOGGING_HOST}:~/maze_server/"
echo ""
echo "# Mini Pupper:"
echo "scp https/maze_https_ros2_bridge.c ${PUPPER_USER}@${PUPPER_HOST}:~/maze_server/"
echo ""
echo "# AI Server:"
echo "scp https/maze_https_redis.c ${AI_USER}@${AI_HOST}:~/maze_server/"
echo ""
echo "# GameHat Controller:"
echo "scp maze/maze_sdl2_final_send.c ${GAMEHAT_USER}@${GAMEHAT_HOST}:~/maze_app/"
echo ""
echo ""

echo "═══════════════════════════════════════════"
echo " TESTING CONNECTIVITY"
echo "═══════════════════════════════════════════"
echo ""
echo "After all servers are running, test from any machine:"
echo ""
echo "# Test Logging Server:"
echo "curl -k -X POST https://${LOGGING_HOST}:8446/telemetry \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"test\":true,\"event_type\":\"connectivity_test\"}'"
echo ""
echo "# Test Mini Pupper:"
echo "curl -k -X POST https://${PUPPER_HOST}:8446/telemetry \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"test\":true,\"event_type\":\"connectivity_test\"}'"
echo ""
echo "# Test AI Server:"
echo "curl -k -X POST https://${AI_HOST}:8446/mission \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"test\":true,\"session_id\":\"test-session\"}'"
echo ""
echo "All tests should return: {\"status\":\"ok\"}"
echo ""
echo "============================================"
echo "  Deployment guide complete!"
echo "============================================"
